
# Project information
site_name: Material 3 Themes for Home Assistant
site_url: https://ha-m3-themes.docs.amoebelabs.com/
site_author: Marco
site_description: >-
  With Material 3 Themes for Home Assistant you can create beautiful combined dark + light themes
  with minimal work and great results!
  <br><br>Create your own theme or use one of the 22 ready-made themes, available in different colors

# Repository
repo_name: amoebelabs/ha-m3-themes
repo_url: https://github.com/amoebelabs/ha-m3-themes
edit_uri: ""

copyright: Copyright &copy; 2021 - 2022 Marco @AmoebeLabs

theme:
  name: material
  palette:
    primary: blue grey
  logo: assets/logo/m3-logo.svg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top   
    - search.suggest
    - search.highlight

plugins:
  - search
  
extra_css:
  - assets/stylesheets/extra.css
  
extra:
  social:
    - icon: bmc/bmc-logo
      link: https://www.buymeacoffee.com/amoebelabs 
    - icon: fontawesome/brands/github
      link: https://github.com/amoebelabs  
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/amoebelabs  
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/amoebelabs  

  analytics:
    provider: google
    property: G-DN0MYXC2JZ

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
  
# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Introduction: start/introduction.md
    - Installation: start/installation.md
    - Changelog: changelog/changelog.md
  - Using HAM3:
      - Compatibility: using/compatibility.md
      - Use in Cards: using/in-cards.md
  - Basics:
    - Color Spaces: basics/color-spaces.md
    - Introducing Material 3:
      - The Color System: basics/m3-color-system.md
      - Dynamic Color aka You!: basics/m3-dynamic-color.md
    - Material 3 Analysis:
      - A new color space: basics/m3-analysis-introduction.md
      - Picking the Hue: basics/m3-analysis-hue-picker.md
      - Theme Palettes: basics/m3-analysis-palettes.md
    - HAM3 Implementation:
      - Introduction: basics/ha-m3-introduction.md
      - Implementation: basics/ha-m3-implementation.md
      - Theme structure: basics/ha-m3-theme-structure.md
      - Theme colors: basics/ha-m3-theme-colors.md
  - Design your OWN:
    - Introduction: design/introduction.md
    - Create an M3 Theme: design/create-m3-theme.md
    - Convert to HA Theme: design/convert-ha-theme.md
  - Examples:
    - Introduction: examples/introduction.md
    - Examples from picture:
      - Theme D01 - Purple: examples/example-d1.md
      - Theme D02 - CadmiumGreen: examples/example-d2.md
      - Theme D03 - Porcupine: examples/example-d3.md
      - Theme D04 - Magenta: examples/example-d4.md
      - Theme D05 - Brown: examples/example-d5.md
      - Theme D06 - TealBlue: examples/example-d6.md
      - Theme D07 - DarkOliveGreen: examples/example-d7.md
      - Theme D08 - Red: examples/example-d8.md
      - Theme D09 - Indigo Blue: examples/example-d9.md
      - Theme D10 - Green: examples/example-d10.md
    - Examples from CIElab colors:
      - Theme C01 - Red: examples/example-c1.md
      - Theme C02 - Volcano: examples/example-c2.md
      - Theme C03 - Orange: examples/example-c3.md
      - Theme C04 - Gold: examples/example-c4.md
      - Theme C05 - Yellow: examples/example-c5.md
      - Theme C06 - Lime: examples/example-c6.md
      - Theme C07 - Green: examples/example-c7.md
      - Theme C08 - Cyan: examples/example-c8.md
      - Theme C09 - Blue: examples/example-c9.md
      - Theme C10 - GeekBlue: examples/example-c10.md
      - Theme C11 - Purple: examples/example-c11.md
      - Theme C12 - Magenta: examples/example-c12.md
